### ISSUE TITLE
Error with Python 3.9

### ISSUE THREAD

**Issue by MinaTangenVolue** [Volue-Public/energy-mesh-python#505]
Mesh Python SDK version: 1.9.0.dev0
Mesh version: Mesh is 2.15.0+3
Python version: 3.9 / 3.11
Operating System (Windows, Ubuntu, etc.): Windows

As discussed with @arkadiuszlis 

I tried running the example script **search_calculation_expression.py** (https://github.com/Volue-Public/energy-mesh-python/blob/master/src/volue/mesh/examples/search_calculation_expressions.py) on internal Volue machines

I get this error using Python 3.9:

```
File "(...) \AppData\Local\Programs\Python\Python39\lib\uuid.py", line 181, in __init__
    raise ValueError('bytes_le is not a 16-char string')
ValueError: bytes_le is not a 16-char string
```

After installing Python 3.11 I do not get this error. It says in the Python SDK documentation that Python 3.9 is supported

**Comment by MinaTangenVolue** [comment]
It works with Python 3.10

**Comment by simia** [comment]
Hi!
I am having problems reproducing this one. Which DB were you using?

**Comment by MinaTangenVolue** [comment]
Yes, that's correct. I also got the error on `axpoprod@mulligan`

**Comment by tnoczyns-volue** [comment]
@MinaTangenVolue we'll need more info to get the repro on devs side. We'll contact you directly.

**Comment by tnoczyns-volue** [comment]
The root cause here was using "old" Mesh Python SDK together with Mesh 2.15 RC. The "old" Mesh Python SDK was installed only in Python 3.9 environment and was lacking: https://github.com/Volue-Public/energy-mesh-python/pull/473.

We confirmed with @MinaTangenVolue that after updating Mesh Python SDK to latest version, it works correctly.
